version: '3.8'

services:
    localstack:
        container_name: "localstack_main"
        image: localstack/localstack:latest
        environment: 
            - SERVICES=s3
            - DOCKER_HOST=unix:///var/run/docker.sock
            - DEFAULT_REGION=eu-north-1
            - DEBUG=1
            # - DATA_DIR=/tmp/localstack/data
        ports:
            - "53:53"
            - "53:53/udp"
            - "443:443"
            - "4566:4566"
            - "4571:4571"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # - ./localstack_data:/tmp/localstack/data
        networks:
            default:
    backend:
        build:
            context: ./backend
        ports:
            - "3000:80"
        networks:
            default:
    frontend:
        build:
            context: ./client
        ports:
            - "3001:3000"
        networks:
            default:

volumes:
    localstack_data:
